config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('vehicle-app-admin-site/', admin.site.urls),
    path('vehiculo/', include('vehiculo.urls'), name='vehicle-app'),
    path('', RedirectView.as_view(url='vehiculo/')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehiculo/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "vehiculo"

urlpatterns = [
    # name is useful for url references in template
    path("", views.IndexView.as_view(), name="index"),
    path("list/", views.VehicleList.as_view(), name="list"),
    path("add/", views.VehicleCreateView.as_view(), name="add-vehicle"),
    path("login/", views.LogUserIn.as_view(), name="login"),
    path("logout/", views.LogUserOut.as_view(), name="logout"),
    path("registro/", views.NewUser.as_view(), name="sign-up"),
    path("update/<int:pk>", views.update_vehiculo, name="update"),
    path("delete/<int:pk>", views.delete_vehiculo, name="delete"),
    path("gallery/<int:pk>", views.gallery_view, name="gallery"),
    path("del-img/<int:pk>", views.delete_img, name="rm-img"),
    path("download/<str:query>", views.download_csv, name="vehicle_csv"),
]

vehiculo/models.py
# Create your models here.
import string
from django.db import models
from django.db.models.functions import Upper
from django.core.validators import MaxValueValidator
from django.core.validators import FileExtensionValidator

class Vehículo(models.Model):

    PARTICULAR = "P"

    TRANSPORTE = "T"

    CARGA = "C"

    ACCEPTED_CATEGORIES = {
        PARTICULAR: "Particular",
        TRANSPORTE: "Transporte",
        CARGA: "Carga",
    }

    marca = models.CharField(verbose_name="marca vehículo", max_length=40, null=False)

    modelo = models.CharField(verbose_name="modelo vehículo", max_length=100, null=False, blank=False)

    carrocería = models.CharField(verbose_name="serial de carrocería", max_length=100, null=False)

    motor = models.CharField(verbose_name="serial de motor", max_length=50, null=False)

    categoría = models.CharField(verbose_name="categoría vehículo", max_length=20, null=False, choices=ACCEPTED_CATEGORIES, 
                                 default=ACCEPTED_CATEGORIES[PARTICULAR])
    
    precio = models.PositiveIntegerField(verbose_name="precio vehículo", null=False, 
                                             validators=[MaxValueValidator(500_000, message="valor debe ser menor o igual a %(limit_value)s")],
                                             help_text="precios entre 0 a 500.000")
    
    creación = models.DateTimeField(verbose_name="fecha creación", auto_now_add=True, editable=False)

    modificación = models.DateTimeField(verbose_name="fecha modificación", auto_now=True)

    class Meta:
        # if verbose name is not specified the name of the model is use
        # if verbose_plural_name is not specified a s is put at the name of the name
        permissions = [
            (
                "visualizar_catalogo",
                "Puede ver la lista de vehículos disponibles",
            ),
            (   "descargar_tabla",
                "Puede descargar la lista de vehículos"),
        ]

        constraints = [
        models.UniqueConstraint(Upper("carrocería"), 
                                name='unique carrocería upper',
                                violation_error_message='La serial de carrocería que intenta ingresar ya existe'),
        models.UniqueConstraint(Upper("motor"), 
                                name='unique motor upper',
                                violation_error_message='La serial de motor que intenta ingresar ya existe'),
        ]
    
    def save(self, *args, **kwargs):
        # only do this if the proper checks are in place 
        # can't do this freely if the field is unique
        # without adding extra constraints you may end
        # up with a lower case entry being turned into 
        # upper before saving but if the upper version is already
        # in the database an error is going to be trigger
        self.marca = string.capwords(self.marca)
        self.modelo = string.capwords(self.modelo)
        self.carrocería = self.carrocería.upper()
        self.motor = self.motor.upper()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return (f"Marca: {self.marca}, Modelo: {self.modelo}, Carrocería: {self.carrocería}, "
                f"Motor: {self.motor}")


class VehículoGalería(models.Model):

    vehículo = models.ForeignKey(Vehículo, on_delete=models.CASCADE, related_name="vehículos")

    descripción = models.CharField(verbose_name="descripción imagen", max_length=150, null=False, error_messages="solo hasta 150 caracteres")

    imágenes = models.ImageField(verbose_name="imágenes vehículo", upload_to="vehículo", 
                                help_text="archivo jpg, png o gif", null=False,
                                validators=[FileExtensionValidator(allowed_extensions=["png", "jpg", "jpeg", "gif",], 
                                                                   message="formatos soportados: png, jpg, jpeg o gif")])
    
    def __str__(self) -> str:
        return f"Vehículo relacionada: {self.vehículo}, Imagen: {self.imágenes.name}"

vehiculo/forms.py
from django import forms
from .models import Vehículo, VehículoGalería
from django.utils.translation import gettext_lazy as alt
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FileUploadForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["descripción"].widget = forms.widgets.Textarea(attrs={"rows": 5})

    class Meta:
        fields = ["imágenes", "descripción"]
        model = VehículoGalería


# para que aparezcan errores si el usuario o contraseña es incorrecto
class LoginForm(AuthenticationForm):

    error_messages = {
        "invalid_login": "Nombre de usuario <br> o contraseña inválidos",
        "inactive": "Acceso denegado",
    }

class VehicleForm(forms.ModelForm):

    # para sobre escribir el comportamiento de ModelForm
    # y que el valor default en html <select> sea el que queramos
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["categoría"].initial = "P"
    
    class Meta:

        model = Vehículo

        # que campos del modelo no se deben mostrar
        exclude = ["creación", "modificación",]

        # mensaje de error si el dato es incorrecto
        error_messages = {
            "precio": {
                "max_value": alt("el valor tiene que ser menor que 500.000"),
            },
        }

class CreateUserForm(UserCreationForm):
    
  
  email = forms.EmailField(required=True)

  def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for item in self.fields:
            self.fields[item].widget.attrs.update({"class": "form-control"})
        self.fields["password1"].help_text = """
    Consideraciones:<br>
    1. Su contraseña no puede ser muy similar a su otra información personal<br>
    2. Su contraseña debe contener al menos 8 caracteres<br>
    3. Su contraseña no puede ser una contraseña de uso común<br>
    4. Su contraseña no puede ser completamente numérica

"""

  class Meta:
      model = User
      fields = ['username', 'email', 'password1', 'password2',]
    

vehiculo/views.py
from pathlib import Path
import csv
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import views as auth_views, authenticate, login
from .forms import VehicleForm, LoginForm, CreateUserForm, FileUploadForm
from .services import fetch_query
from django.contrib import messages
from .models import Vehículo, VehículoGalería
from django.forms.models import model_to_dict
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required

# Create your views here.

# PermissionRequiredMixin es para evitar en este caso que
# se trate de acceder a la ruta escribiendo la url manual
class VehicleList(PermissionRequiredMixin, generic.ListView):

    # template de la ruta
    template_name = 'vehiculo/list.html'

    # nombre para referirse a valores pasados al template
    context_object_name = 'list_of_vehicles'

    # permisos que PermissionRequiredMixin va revisar
    # que tenga el usuario
    permission_required = 'vehiculo.visualizar_catalogo'

    # donde redirige si un usuario no registrado y autorizado quiere entrar
    # si un usuario registrado pero no autorizado intenta entrar se le da un error
    # 403 y no se le redirige al login
    login_url = "vehiculo:login"

    redirect_field_name = "redirect_to"

    # sql de consulta al modelo que se retorna al template
    # Case es igual que a los condicionales de postsgresql
    # en Case cada condición se escribe usando When
    # cosas como precio__gte significa del modelo Vehículo
    # en el atributo precio usa el método __gte__ (greater or equal than)
    # then es el valor que se va a pasar cuando se cumpla la condicional
    # condición= es el nombre del Case para referirse a el en el template
    def get_queryset(self):
        return fetch_query(self.request.GET.get("resultados", None))
    
    # para pasar datos extras al template en este caso tomamos
    # los nombres de los campos o atributos del modelo para usarlos como encabezado de tabla
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # django creates an aditional field to the model related to this one
        # with related_name set the relation in vehículo to vehículogalería
        # changes from vehículogalería to vehículos
        context["header"] = [field.verbose_name for field in Vehículo._meta.get_fields()
                             if field.name not in("id", "creación", "modificación", "vehículos")]
        context["header"].extend(["Condición de precio",])
        if (download_context := self.request.GET.get("resultados", False)):
            context["download"] = download_context
        else:
            context["download"] = "all"
        return context


class IndexView(generic.TemplateView):

    template_name = 'vehiculo/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_authorized"] = self.request.user.has_perm("vehiculo.add_vehículo")
        return context


class VehicleCreateView(PermissionRequiredMixin, CreateView):

    # defino la clase de forma a usar desde forms.py

    model = Vehículo

    form_class = VehicleForm

    template_name = "vehiculo/add.html"

    permission_required = 'vehiculo.add_vehículo'

    login_url = "vehiculo:login"

    redirect_field_name = "redirect_to"

    # mensaje de entrada creada con éxito, de forma
    # habitual si un usuario con ambos poderes add_vehículo 
    # y visualizar_catalogo crea una entrada se redirige a la
    # lista de todas las entradas lo que en si es su mensaje 
    # de éxito pero si no tiene el permiso visualizar_catalogo
    # se le tiene que enviar de vuelta al formulario y para
    # que tenga una idea de que el formulario fue exitoso
    # se requiere este mensaje y la clase SuccessMessageMixin

    # ruta a la que se redirige si el formulario es valido
    # en mi caso después de crear cada entrada redirijo a la
    # lista de entradas
    def get_success_url(self) -> str:
        new_entry = model_to_dict(instance=get_object_or_404(Vehículo, pk=self.object.id), exclude=["id", "creación", "modificación",])
        new_entry = ", ".join([f"{key}: {value}" for key, value in new_entry.items()])
        messages.success(self.request, f"Entrada creada exitosamente<br> {new_entry}", "éxito")
        return reverse("vehiculo:add-vehicle")

    

class LogUserIn(auth_views.LoginView):

    template_name = "registration/login.html"

    next_page = "vehiculo:index"

    # defino la clase de forma a usar desde forms.py
    authentication_form = LoginForm

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(redirect_to=reverse(f"vehiculo:index"), status = 302)
    


class LogUserOut(auth_views.LogoutView):

    # donde se redirige después de salir de la cuenta
    next_page = "vehiculo:index"

    # message on log out
    def get_success_url(self):
        messages.success(self.request, "sesión cerrada", "éxito")
        return super().get_success_url()


class NewUser(SuccessMessageMixin, CreateView):

    form_class = CreateUserForm

    template_name = 'registration/signup.html'

    success_message = "usuario creado exitosamente"

    # this is how get method is overwritten in class view
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(redirect_to=reverse(f"vehiculo:index"), status = 302)

    # necessary to log user in after creation
    def form_valid(self, form):
        valid = super().form_valid(form)
        # group do not have a codename unlike permissions
        try:
            permission_group = Group.objects.get(name="usuario")
        except Group.DoesNotExist:
            pass
        else:
            self.object.groups.add(permission_group)
        # you can actually do this
        # for adding one permission do this self.object.user_permissions.add(permission_user)
        # to add to a group do this:
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        if new_user is not None:
            login(self.request, new_user)
        return valid

    def get_success_url(self):
        return reverse("vehiculo:index")

@login_required(login_url=reverse_lazy("vehiculo:login"))   
def update_vehiculo(request, pk):
    
    # so you can write the url to update manually
    # HTTP_HX_REQUEST this tells that it is htmx
    if request.META.get("HTTP_HX_REQUEST", False):
        if request.method == "GET":
            edit_vehiculo = get_object_or_404(Vehículo, pk=pk)
            form = VehicleForm(instance=edit_vehiculo)
            context = {"form": form,}
            return render(request, "vehiculo/edit.html", context)
        elif request.method == "POST":
            edit_vehiculo = get_object_or_404(Vehículo, pk=pk)
            # this way you can update using a functional way
            # print(request.POST) is the data obtained from the form
            # the instance is the one to update
            form = VehicleForm(request.POST, instance=edit_vehiculo)
            if form.is_valid():
                form.save()
                messages.success(request, "entrada actualizada exitosamente", "éxito")
                # how to manage redirect ajax pass response with url and redirect in js
                # this for redirect with htmx
                new_response = HttpResponse()
                new_response["HX-Redirect"] = reverse("vehiculo:list")
                return new_response
            else:
                context = {"form": form}
                return render(request, "vehiculo/edit.html", context, status=200)
    raise PermissionDenied
    
@login_required(login_url=reverse_lazy("vehiculo:login"))
def delete_vehiculo(request, pk):
    if request.META.get("HTTP_HX_REQUEST", False):
        if request.method == "DELETE":
            delete_vehiculo = get_object_or_404(Vehículo, pk=pk)
            old_entry = model_to_dict(instance=delete_vehiculo, exclude=["id", "creación", "modificación",])
            old_entry["categoría"] = delete_vehiculo.get_categoría_display()
            old_entry = ", ".join([f"{key}: {value}" for key, value in old_entry.items()])
            related_gallery = VehículoGalería.objects.all().filter(vehículo=pk)
            for entry in related_gallery:
                Path(entry.imágenes.path).unlink()
            delete_vehiculo.delete()
            messages.success(request, f"Entrada borrada exitosamente<br> {old_entry}", "éxito")
            new_response = HttpResponse()
            new_response["HX-Redirect"] = reverse("vehiculo:list")
            return new_response
        elif request.method == "GET":
            context = {"entry": pk}
            return render(request, "vehiculo/delete.html", context)
    raise PermissionDenied
    
@login_required(login_url=reverse_lazy("vehiculo:login"))
def gallery_view(request, pk):
    if "vehiculo.view_vehículogalería" not in request.user.get_all_permissions():
        raise PermissionDenied
    # global context
    try:
        current_element = Vehículo.objects.get(pk=pk)
    except Vehículo.DoesNotExist:
        return HttpResponseRedirect(redirect_to=reverse(f"vehiculo:list"), status = 302)

vehiculo/templates/vehiculo/delete.html
<button class="cerrar" onclick="document.getElementById('change_target').close();">X</button>
<div class="align-self-center d-flex flex-column text-center" id="delete_vehicle">
    <h6>Presione el botón para confirmar</h6>
    <button class="btn btn-secondary btn-md limit" hx-delete="{% url 'vehiculo:delete' pk=entry %}">Borrar</button>
</div>

vehiculo/templates/vehiculo/edit.html
<div class="d-flex flex-column align-items-center" id="edit_vehicle">
    <button class="cerrar" onclick="document.getElementById('change_target').close();">X</button>
    <h1>Actualizar</h1>
    <form hx-post="{% url 'vehiculo:update' pk=form.instance.pk %}"  hx-target="#change_target" hx-swap="innerHTML" class="d-flex flex-column align-items-start" id="table_action">
        <!-- token seguridad -->
        {% csrf_token %}
        <!-- itera sobre los elementos de la form de django -->
        {% for field in form %}
        <div class="my-2">
            {% if field.errors %}
            <div class="alert alert-danger text-center" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>
            {% endif %}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help my-1 text-end" id="{{ field.auto_id }}_helptext">
                {{ field.help_text}}
            </p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="align-self-center">
            <button class="btn btn-secondary btn-lg">Actualizar</button>
        </div>
    </form>
</div>

vehiculo/templates/vehiculo/footer.html
<footer class="text-center my-3 mx-auto">
    <small>Sitio creado por Lucas Folch 2024 &#xa9; todos los derechos reservados</small>
</footer>

vehiculo/templates/vehiculo/list.html
{% extends "vehiculo/base.html" %}
{% block title %}
Listado de Vehículos
{% endblock title %}
{% block content %}
<main>
    <div class="w-100 text-center">
        {% if messages %}
        {% for message in messages %}
        <!--message.tags return the type of message success error warnings, etc-->
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message|safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {% if list_of_vehicles %}
    <div class="mx-2 overflow-auto">
        <div class="d-flex flex-row flex-wrap mt-2">
            <h3 class="me-auto">Listado de vehículos</h3>
            <form action="" method="GET" id="búsqueda">
                <input name="resultados" type="text" placeholder="Buscar marca o vehículo" id="vehículo-resultado">
                <input class="btn btn-secondary" type="submit" value="Buscar">
            </form>
        </div>
        <table class="table my-2 mx-auto">
            <thead class="table-dark">
                <tr>
                    {% for key in header %}
                        <th>{{ key|title }}</th>
                    {% endfor %}
                    {% if perms.vehiculo.view_vehículogalería %}
                        <th>Galería</th>
                    {% endif %}
                    {% if perms.vehiculo.change_vehículo %}
                        <th>Editar</th>
                    {% endif %}
                    {% if perms.vehiculo.delete_vehículo %}
                        <th>Eliminar</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for entry in list_of_vehicles %}
                <tr>
                    <!--get_<nombre_campo_modelo>_display para obtener el valor de un campo
                        si este no es fácilmente entendible para el usuario recomendable en
                        campos que usan el argumento choice -->
                    <td>{{ entry.marca }}</td>
                    <td>{{ entry.modelo }}</td>
                    <td>{{ entry.carrocería }}</td>
                    <td>{{ entry.motor }}</td>
                    <td>{{ entry.get_categoría_display }}</td>
                    <td>{{ entry.precio }}</td>
                    <td>{{ entry.condición }}</td>
                    {% if perms.vehiculo.view_vehículogalería %}
                        <td><a class="btn btn-primary" href="{% url 'vehiculo:gallery' pk=entry.pk %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-image" viewBox="0 0 16 16">
                                <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/>
                                <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54L1 12.5v-9a.5.5 0 0 1 .5-.5z"/>
                              </svg>
                            </a></td>
                    {% endif %}
                    {% if perms.vehiculo.change_vehículo %}
                        <td><button type="button" class="btn btn-primary" hx-get="{% url 'vehiculo:update' pk=entry.pk %}"  hx-target="#change_target" hx-swap="innerHTML">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
                              </svg>
                        </button></td>
                    {% endif %}
                    {% if perms.vehiculo.delete_vehículo %}
                        <td><button type="button" class="btn btn-danger" hx-get="{% url 'vehiculo:delete' pk=entry.pk %}"  hx-target="#change_target" hx-swap="innerHTML">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
                              </svg>
                        </button></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% if perms.vehiculo.descargar_tabla %}
        <div class="my-2 text-center">
            <a href="{% url 'vehiculo:vehicle_csv' query=download %}" download class="link-success link h5">descargar datos actuales tabla
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filetype-csv" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5zM3.517 14.841a1.13 1.13 0 0 0 .401.823q.195.162.478.252.284.091.665.091.507 0 .859-.158.354-.158.539-.44.187-.284.187-.656 0-.336-.134-.56a1 1 0 0 0-.375-.357 2 2 0 0 0-.566-.21l-.621-.144a1 1 0 0 1-.404-.176.37.37 0 0 1-.144-.299q0-.234.185-.384.188-.152.512-.152.214 0 .37.068a.6.6 0 0 1 .246.181.56.56 0 0 1 .12.258h.75a1.1 1.1 0 0 0-.2-.566 1.2 1.2 0 0 0-.5-.41 1.8 1.8 0 0 0-.78-.152q-.439 0-.776.15-.337.149-.527.421-.19.273-.19.639 0 .302.122.524.124.223.352.367.228.143.539.213l.618.144q.31.073.463.193a.39.39 0 0 1 .152.326.5.5 0 0 1-.085.29.56.56 0 0 1-.255.193q-.167.07-.413.07-.175 0-.32-.04a.8.8 0 0 1-.248-.115.58.58 0 0 1-.255-.384zM.806 13.693q0-.373.102-.633a.87.87 0 0 1 .302-.399.8.8 0 0 1 .475-.137q.225 0 .398.097a.7.7 0 0 1 .272.26.85.85 0 0 1 .12.381h.765v-.072a1.33 1.33 0 0 0-.466-.964 1.4 1.4 0 0 0-.489-.272 1.8 1.8 0 0 0-.606-.097q-.534 0-.911.223-.375.222-.572.632-.195.41-.196.979v.498q0 .568.193.976.197.407.572.626.375.217.914.217.439 0 .785-.164t.55-.454a1.27 1.27 0 0 0 .226-.674v-.076h-.764a.8.8 0 0 1-.118.363.7.7 0 0 1-.272.25.9.9 0 0 1-.401.087.85.85 0 0 1-.478-.132.83.83 0 0 1-.299-.392 1.7 1.7 0 0 1-.102-.627zm8.239 2.238h-.953l-1.338-3.999h.917l.896 3.138h.038l.888-3.138h.879z"/>
                </svg>
            </a>
        </div>
    {% endif %}
        {% else %}
        <div class="text-center">
        <h3>No hay vehículos disponibles</h3>
        </div>
        {% endif %}
</main>
<!--to do an action after an htmx even use hx-on:: on the target of the action-->
<dialog id="change_target" hx-on::after-swap="document.getElementById('change_target').show();">
</dialog>
{% endblock content %}

vehiculo/templates/vehiculo/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Vehículos</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" aria-current="page" href="{% url 'vehiculo:index' %}">Inicio</a>
        <!--asi puedo ver que permiso tiene el usuario desde un template-->
        {% if perms.vehiculo.add_vehículo %}
        <a class="nav-link" href="{% url 'vehiculo:add-vehicle' %}">Agregar</a>
        {% endif %}
        {% if perms.vehiculo.visualizar_catalogo %}
        <a class="nav-link" href="{% url 'vehiculo:list' %}">Listar</a>
        {% endif %}
      </div>
      <div class="navbar-nav ms-auto">
        <!--para ver si el usuario esta registrado-->
        {% if request.user.is_authenticated %}
        <form action="{% url 'vehiculo:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="nav-link">Salir</button>
        </form>
        <small class="nav-link active">Hola, {{ request.user.username }}</small>
        {% else %}
        <a class="nav-link" href="{% url 'vehiculo:login' %}">Entrar</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>